import '../../core/app_error.dart';
import '../../core/result.dart';
import '../memory/memory_retriever.dart';
import '../memory/memory_types.dart';
import '../refine/llm_runner.dart';
import '../search/hybrid_retriever.dart';
import 'ask_prompt_templates.dart';
import 'ask_query_utils.dart';
import 'ask_stream_guard.dart';

/// Searches active local memory cards for ask-context.
typedef AskMemorySearch =
    Future<Result<List<MemoryHit>, MemoryRetrieverError>> Function(
      String query, {
      int limit,
    });

/// Searches voice logs for ask-context.
typedef AskLogSearch =
    Future<Result<List<SearchHit>, RetrieverError>> Function(
      String query, {
      int limit,
    });

/// Answer returned by the local ask assistant with the context used to produce
/// it, so the UI can show transparent grounding.
class AskAnswer {
  const AskAnswer({
    required this.question,
    required this.answer,
    required this.memoryHits,
    required this.logHits,
  });

  /// User question after trimming whitespace.
  final String question;

  /// Assistant response generated by the local LLM, or a deterministic
  /// no-context response when retrieval finds nothing.
  final String answer;

  /// Memory cards supplied to the answer prompt.
  final List<MemoryHit> memoryHits;

  /// Voice-log snippets supplied to the answer prompt.
  final List<SearchHit> logHits;
}

/// Events emitted while a local ask response is being prepared and streamed.
sealed class AskStreamEvent {
  const AskStreamEvent();
}

/// Retrieval completed and the prompt context is known.
final class AskContextReady extends AskStreamEvent {
  const AskContextReady({required this.memoryHits, required this.logHits});

  /// Memory cards that will be supplied to the answer prompt.
  final List<MemoryHit> memoryHits;

  /// Voice-log snippets that will be supplied to the answer prompt.
  final List<SearchHit> logHits;
}

/// A text delta from the local LLM.
final class AskAnswerDelta extends AskStreamEvent {
  const AskAnswerDelta(this.text);

  /// Newly generated text.
  final String text;
}

/// The answer is complete.
final class AskAnswerDone extends AskStreamEvent {
  const AskAnswerDone(this.answer);

  /// Final cleaned answer and the context used to generate it.
  final AskAnswer answer;
}

/// Errors from the local ask flow.
sealed class AskError extends AppError {
  const AskError({required super.message, super.cause, super.stack});
}

/// The question was empty after trimming.
final class AskValidationError extends AskError {
  const AskValidationError() : super(message: 'Type a question first.');
}

/// Retrieval failed before the LLM could be prompted.
final class AskRetrievalError extends AskError {
  const AskRetrievalError({required super.message, super.cause, super.stack});
}

/// Local LLM generation failed.
final class AskLlmError extends AskError {
  const AskLlmError({required super.message, super.cause, super.stack});
}

/// Local retrieval-augmented assistant for asking questions over voice logs and
/// active memory cards. All retrieval and generation stays on-device.
class AskAssistant {
  const AskAssistant({
    required LlmRunner runner,
    required AskMemorySearch searchMemories,
    required AskLogSearch searchLogs,
    int memoryLimit = kAskPromptMemoryLimit,
    int logLimit = kAskPromptLogLimit,
  }) : _runner = runner,
       _searchMemories = searchMemories,
       _searchLogs = searchLogs,
       _memoryLimit = memoryLimit,
       _logLimit = logLimit;

  final LlmRunner _runner;
  final AskMemorySearch _searchMemories;
  final AskLogSearch _searchLogs;
  final int _memoryLimit;
  final int _logLimit;

  /// Retrieve context for [question] and answer it with the serialized local
  /// LLM. If no context is found, no LLM call is made.
  Future<Result<AskAnswer, AskError>> ask(String question) async {
    AskAnswer? completed;
    await for (final event in askStream(question)) {
      switch (event) {
        case Ok(:final value):
          if (value case AskAnswerDone(:final answer)) {
            completed = answer;
          }
        case Err(:final error):
          return Err(error);
      }
    }
    final answer = completed;
    if (answer == null) {
      return const Err(AskLlmError(message: 'Ask generation ended early.'));
    }
    return Ok(answer);
  }

  /// Retrieve context for [question] and stream answer deltas as the local LLM
  /// generates them.
  Stream<Result<AskStreamEvent, AskError>> askStream(String question) async* {
    final trimmed = question.trim();
    if (trimmed.isEmpty) {
      yield const Err(AskValidationError());
      return;
    }

    final retrievalQuery = buildAskRetrievalQuery(trimmed);
    final (memoryResult, logResult) = await (
      _searchMemories(retrievalQuery, limit: _memoryLimit),
      _searchLogs(retrievalQuery, limit: _logLimit),
    ).wait;

    final List<MemoryHit> memories;
    switch (memoryResult) {
      case Ok(:final value):
        memories = value;
      case Err():
        memories = const [];
    }

    final List<SearchHit> logs;
    switch (logResult) {
      case Ok(:final value):
        logs = value;
      case Err():
        logs = const [];
    }

    if (memories.isEmpty && logs.isEmpty) {
      if (memoryResult case Err(:final error)) {
        yield Err(
          AskRetrievalError(
            message: 'Retrieval failed: ${error.message}',
            cause: error,
            stack: error.stack,
          ),
        );
        return;
      }
      if (logResult case Err(:final error)) {
        yield Err(
          AskRetrievalError(
            message: 'Retrieval failed: ${error.message}',
            cause: error,
            stack: error.stack,
          ),
        );
        return;
      }
    }

    yield Ok(AskContextReady(memoryHits: memories, logHits: logs));

    if (memories.isEmpty && logs.isEmpty) {
      const noContext =
          "I don't have enough context from your voice logs to answer "
          'that.\n\n'
          'No matching voice logs or memories were retrieved.';
      yield const Ok(AskAnswerDelta(noContext));
      yield Ok(
        AskAnswerDone(
          AskAnswer(
            question: trimmed,
            answer: noContext,
            memoryHits: const [],
            logHits: const [],
          ),
        ),
      );
      return;
    }

    final prompt = buildAskPrompt(
      question: trimmed,
      memoryHits: memories,
      logHits: logs,
    );
    final out = StringBuffer();
    final guard = AskStreamGuard();
    AskStreamGuardTrip? tripReason;
    if (_runner case final StreamingLlmRunner streamingRunner) {
      streamLoop:
      await for (final chunkResult in streamingRunner.generateStream(
        prompt,
        temperature: _kAskTemperature,
        topK: _kAskTopK,
      )) {
        switch (chunkResult) {
          case Ok(:final value):
            out.write(value);
            yield Ok(AskAnswerDelta(value));
            tripReason = guard.inspect(out.toString());
            if (tripReason != null) break streamLoop;
          case Err(:final error):
            yield Err(_llmError(error));
            return;
        }
      }
    } else {
      final answerResult = await _runner.generate(
        prompt,
        temperature: _kAskTemperature,
        topK: _kAskTopK,
      );
      switch (answerResult) {
        case Ok(:final value):
          // The non-streaming path already has the full response, so apply
          // the guard once and truncate if it tripped before yielding the
          // delta. This keeps a runaway one-shot answer from blasting a
          // multi-megabyte string into the UI.
          final truncated = _truncateOneShot(value, guard);
          out.write(truncated.text);
          yield Ok(AskAnswerDelta(truncated.text));
          tripReason = truncated.trip;
        case Err(:final error):
          yield Err(_llmError(error));
          return;
      }
    }

    if (tripReason != null) {
      out.write(AskStreamGuard.truncationMarker);
      yield const Ok(AskAnswerDelta(AskStreamGuard.truncationMarker));
    }

    final raw = out.toString();
    final finalAnswer = AskAnswer(
      question: trimmed,
      answer: _cleanAnswer(
        _validateCitations(raw, memories.length, logs.length),
      ),
      memoryHits: memories,
      logHits: logs,
    );
    yield Ok(AskAnswerDone(finalAnswer));
  }
}

/// Sampling parameters for Ask, matching the Gemma 3 team's published
/// recommendation (temperature=1.0, topK=64, topP=0.95). The previous
/// config (temperature=0.35, topK=1) was the actual root cause of the
/// phrase-loop bug: flutter_gemma defaults [topK] to 1, which forces
/// purely greedy decoding regardless of temperature. Temperature only
/// matters when topK lets multiple candidates into the sampling pool.
///
/// Refine deliberately keeps the greedy defaults (temperature=0.0,
/// topK=1) so its JSON output stays deterministic and parseable.
const double _kAskTemperature = 1.0;
const int _kAskTopK = 64;
// topP=0.95 is Gemma's recommendation and also the LlmRunner default, so
// we don't pass it explicitly — keep the constant available for tests that
// want to assert the documented value.
const double _kAskTopP = 0.95; // ignore: unused_element

/// Result of applying the stream guard to a non-streaming response. The
/// returned [text] is the answer truncated at the first guard trip, with
/// trailing word-boundary alignment so it doesn't end mid-token.
({String text, AskStreamGuardTrip? trip}) _truncateOneShot(
  String answer,
  AskStreamGuard guard,
) {
  // Walk the answer in modestly-sized slices so the guard sees the same
  // tail shape it would in the streaming case. Stops at the first trip.
  const sliceChars = 80;
  final buffer = StringBuffer();
  for (var i = 0; i < answer.length; i += sliceChars) {
    final end = (i + sliceChars).clamp(0, answer.length);
    buffer.write(answer.substring(i, end));
    final trip = guard.inspect(buffer.toString());
    if (trip != null) {
      return (text: buffer.toString(), trip: trip);
    }
  }
  return (text: answer, trip: null);
}

AskLlmError _llmError(LlmError error) {
  return AskLlmError(
    message: 'Ask generation failed: ${error.message}',
    cause: error,
    stack: error.stack,
  );
}

String _cleanAnswer(String raw) {
  final trimmed = raw.trim();
  if (trimmed.isEmpty) {
    return 'I found relevant context but the on-device model '
        'returned an empty answer.';
  }
  return trimmed.trim();
}

String _validateCitations(String answer, int memoryCount, int logCount) {
  return answer.replaceAllMapped(RegExp(r'\[([ML])(\d+)\]'), (match) {
    final type = match.group(1)!;
    final num = int.parse(match.group(2)!);
    final max = type == 'M' ? memoryCount : logCount;
    return num <= max ? match.group(0)! : '';
  });
}
