import '../../core/app_error.dart';
import '../../core/result.dart';
import '../memory/memory_retriever.dart';
import '../memory/memory_types.dart';
import '../refine/llm_runner.dart';
import '../search/hybrid_retriever.dart';
import 'ask_prompt_templates.dart';

/// Searches active local memory cards for ask-context.
typedef AskMemorySearch =
    Future<Result<List<MemoryHit>, MemoryRetrieverError>> Function(
      String query, {
      int limit,
    });

/// Searches voice logs for ask-context.
typedef AskLogSearch =
    Future<Result<List<SearchHit>, RetrieverError>> Function(
      String query, {
      int limit,
    });

/// Answer returned by the local ask assistant with the context used to produce
/// it, so the UI can show transparent grounding.
class AskAnswer {
  const AskAnswer({
    required this.question,
    required this.answer,
    required this.memoryHits,
    required this.logHits,
  });

  /// User question after trimming whitespace.
  final String question;

  /// Assistant response generated by the local LLM, or a deterministic
  /// no-context response when retrieval finds nothing.
  final String answer;

  /// Memory cards supplied to the answer prompt.
  final List<MemoryHit> memoryHits;

  /// Voice-log snippets supplied to the answer prompt.
  final List<SearchHit> logHits;
}

/// Events emitted while a local ask response is being prepared and streamed.
sealed class AskStreamEvent {
  const AskStreamEvent();
}

/// Retrieval completed and the prompt context is known.
final class AskContextReady extends AskStreamEvent {
  const AskContextReady({required this.memoryHits, required this.logHits});

  /// Memory cards that will be supplied to the answer prompt.
  final List<MemoryHit> memoryHits;

  /// Voice-log snippets that will be supplied to the answer prompt.
  final List<SearchHit> logHits;
}

/// A text delta from the local LLM.
final class AskAnswerDelta extends AskStreamEvent {
  const AskAnswerDelta(this.text);

  /// Newly generated text.
  final String text;
}

/// The answer is complete.
final class AskAnswerDone extends AskStreamEvent {
  const AskAnswerDone(this.answer);

  /// Final cleaned answer and the context used to generate it.
  final AskAnswer answer;
}

/// Errors from the local ask flow.
sealed class AskError extends AppError {
  const AskError({required super.message, super.cause, super.stack});
}

/// The question was empty after trimming.
final class AskValidationError extends AskError {
  const AskValidationError() : super(message: 'Type a question first.');
}

/// Retrieval failed before the LLM could be prompted.
final class AskRetrievalError extends AskError {
  const AskRetrievalError({required super.message, super.cause, super.stack});
}

/// Local LLM generation failed.
final class AskLlmError extends AskError {
  const AskLlmError({required super.message, super.cause, super.stack});
}

/// Local retrieval-augmented assistant for asking questions over voice logs and
/// active memory cards. All retrieval and generation stays on-device.
class AskAssistant {
  const AskAssistant({
    required LlmRunner runner,
    required AskMemorySearch searchMemories,
    required AskLogSearch searchLogs,
    int memoryLimit = kAskPromptMemoryLimit,
    int logLimit = 10,
  }) : _runner = runner,
       _searchMemories = searchMemories,
       _searchLogs = searchLogs,
       _memoryLimit = memoryLimit,
       _logLimit = logLimit;

  final LlmRunner _runner;
  final AskMemorySearch _searchMemories;
  final AskLogSearch _searchLogs;
  final int _memoryLimit;
  final int _logLimit;

  /// Retrieve context for [question] and answer it with the serialized local
  /// LLM. If no context is found, no LLM call is made.
  Future<Result<AskAnswer, AskError>> ask(String question) async {
    AskAnswer? completed;
    await for (final event in askStream(question)) {
      switch (event) {
        case Ok(:final value):
          if (value case AskAnswerDone(:final answer)) {
            completed = answer;
          }
        case Err(:final error):
          return Err(error);
      }
    }
    final answer = completed;
    if (answer == null) {
      return const Err(AskLlmError(message: 'Ask generation ended early.'));
    }
    return Ok(answer);
  }

  /// Retrieve context for [question] and stream answer deltas as the local LLM
  /// generates them.
  Stream<Result<AskStreamEvent, AskError>> askStream(String question) async* {
    final trimmed = question.trim();
    if (trimmed.isEmpty) {
      yield const Err(AskValidationError());
      return;
    }

    final (memoryResult, logResult) = await (
      _searchMemories(trimmed, limit: _memoryLimit),
      _searchLogs(trimmed, limit: _logLimit),
    ).wait;

    final List<MemoryHit> memories;
    switch (memoryResult) {
      case Ok(:final value):
        memories = value;
      case Err():
        memories = const [];
    }

    final List<SearchHit> logs;
    switch (logResult) {
      case Ok(:final value):
        logs = value;
      case Err():
        logs = const [];
    }

    if (memories.isEmpty && logs.isEmpty) {
      if (memoryResult case Err(:final error)) {
        yield Err(
          AskRetrievalError(
            message: 'Retrieval failed: ${error.message}',
            cause: error,
            stack: error.stack,
          ),
        );
        return;
      }
      if (logResult case Err(:final error)) {
        yield Err(
          AskRetrievalError(
            message: 'Retrieval failed: ${error.message}',
            cause: error,
            stack: error.stack,
          ),
        );
        return;
      }
    }

    yield Ok(AskContextReady(memoryHits: memories, logHits: logs));

    if (memories.isEmpty && logs.isEmpty) {
      const noContext =
          "I don't have enough context from your voice logs to answer "
          'that.\n\n'
          'No matching voice logs or memories were retrieved.';
      yield const Ok(AskAnswerDelta(noContext));
      yield Ok(
        AskAnswerDone(
          AskAnswer(
            question: trimmed,
            answer: noContext,
            memoryHits: const [],
            logHits: const [],
          ),
        ),
      );
      return;
    }

    final prompt = buildAskPrompt(
      question: trimmed,
      memoryHits: memories,
      logHits: logs,
    );
    final out = StringBuffer();
    if (_runner case final StreamingLlmRunner streamingRunner) {
      await for (final chunkResult in streamingRunner.generateStream(
        prompt,
        temperature: 0.2,
      )) {
        switch (chunkResult) {
          case Ok(:final value):
            out.write(value);
            yield Ok(AskAnswerDelta(value));
          case Err(:final error):
            yield Err(_llmError(error));
            return;
        }
      }
    } else {
      final answerResult = await _runner.generate(prompt, temperature: 0.2);
      switch (answerResult) {
        case Ok(:final value):
          out.write(value);
          yield Ok(AskAnswerDelta(value));
        case Err(:final error):
          yield Err(_llmError(error));
          return;
      }
    }

    final raw = out.toString();
    final finalAnswer = AskAnswer(
      question: trimmed,
      answer: _cleanAnswer(
        _validateCitations(raw, memories.length, logs.length),
      ),
      memoryHits: memories,
      logHits: logs,
    );
    yield Ok(AskAnswerDone(finalAnswer));
  }
}

AskLlmError _llmError(LlmError error) {
  return AskLlmError(
    message: 'Ask generation failed: ${error.message}',
    cause: error,
    stack: error.stack,
  );
}

String _cleanAnswer(String raw) {
  var trimmed = raw.trim();
  if (trimmed.isEmpty) {
    return 'I found relevant context but the on-device model '
        'returned an empty answer.';
  }
  trimmed = trimmed.replaceFirst(
    RegExp(r'\n##\s*(Key points|Gaps|Notes|Additional)[\s\S]*$'),
    '',
  );
  return trimmed.trim();
}

String _validateCitations(String answer, int memoryCount, int logCount) {
  return answer.replaceAllMapped(RegExp(r'\[([ML])(\d+)\]'), (match) {
    final type = match.group(1)!;
    final num = int.parse(match.group(2)!);
    final max = type == 'M' ? memoryCount : logCount;
    return num <= max ? match.group(0)! : '';
  });
}
