// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `s16le_to_f32`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Load the Parakeet-TDT model sitting under `model_dir`. Expects the
/// sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8 layout:
///
/// ```text
/// model_dir/
///   encoder.int8.onnx
///   decoder.int8.onnx
///   joiner.int8.onnx
///   tokens.txt
/// ```
///
/// Returns a human-readable error on failure (frb maps `Result<_, String>`
/// into Dart exceptions we'll catch and re-box as `ModelLoadError`).
Future<void> loadParakeet({
  required String modelDir,
  required int numThreads,
}) => RustLib.instance.api.crateApiAsrLoadParakeet(
  modelDir: modelDir,
  numThreads: numThreads,
);

/// Transcribe a 16 kHz signed-16-bit little-endian PCM buffer.
///
/// Returns the transcript plus the detected language (always `"en"` for
/// Parakeet-TDT-0.6B-v2 — preserved for interface stability with future
/// multilingual models).
Future<TranscriptDto> transcribePcmS16Le({required List<int> pcm}) =>
    RustLib.instance.api.crateApiAsrTranscribePcmS16Le(pcm: pcm);

/// Drop the loaded recognizer. Safe to call multiple times.
Future<void> dispose() => RustLib.instance.api.crateApiAsrDispose();

/// `true` when a recognizer is loaded — used by Dart-side lifecycle tests.
Future<bool> isLoaded() => RustLib.instance.api.crateApiAsrIsLoaded();

/// DTO returned to Dart.
class TranscriptDto {
  final String text;
  final String detectedLanguage;

  const TranscriptDto({required this.text, required this.detectedLanguage});

  @override
  int get hashCode => text.hashCode ^ detectedLanguage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          detectedLanguage == other.detectedLanguage;
}
