// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `l2_normalize`, `mean_pool`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `E5Session`

/// Load the e5 model.
///
/// `weights_path` → `model.safetensors` (fp32 from HF, loaded as F16 in
/// memory), `config_path` → `config.json`, `tokenizer_path` →
/// `tokenizer.json`.
Future<void> loadE5({
  required String weightsPath,
  required String configPath,
  required String tokenizerPath,
}) => RustLib.instance.api.crateApiEmbedLoadE5(
  weightsPath: weightsPath,
  configPath: configPath,
  tokenizerPath: tokenizerPath,
);

/// Embed a batch of strings. Callers must add `"query: "` or `"passage: "`
/// before calling — the Dart `Embedder` interface does that for us.
///
/// Returns one 384-d L2-normalised vector per input, in order.
Future<List<Float32List>> embedBatch({required List<String> texts}) =>
    RustLib.instance.api.crateApiEmbedEmbedBatch(texts: texts);

Future<void> disposeEmbedder() =>
    RustLib.instance.api.crateApiEmbedDisposeEmbedder();

Future<bool> isE5Loaded() => RustLib.instance.api.crateApiEmbedIsE5Loaded();
