// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_tokens`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GemmaSession`

/// Load a quantized Gemma 3 model + its tokenizer.
///
/// `model_path`: path to a GGUF file (`*.gguf`).
/// `tokenizer_path`: path to a `tokenizer.json` produced by the
/// `tokenizers` crate (Gemma 3's official tokenizer works as-is).
Future<void> loadGemma({
  required String modelPath,
  required String tokenizerPath,
}) => RustLib.instance.api.crateApiLlmLoadGemma(
  modelPath: modelPath,
  tokenizerPath: tokenizerPath,
);

/// Generate a completion for [`prompt`]. Returns the generated text
/// only — the prompt itself is not echoed.
///
/// Sampling: greedy when `temperature <= 0`, temperature-only otherwise.
/// `max_tokens` caps the generation length; a `repeat_penalty` of 1.1
/// is applied over the last 64 tokens (matching candle's example
/// defaults, which avoid Gemma's common repeat-loop failure mode).
Future<String> generateSync({
  required String prompt,
  required int maxTokens,
  required double temperature,
}) => RustLib.instance.api.crateApiLlmGenerateSync(
  prompt: prompt,
  maxTokens: maxTokens,
  temperature: temperature,
);

/// Drop the loaded model. Safe to call multiple times.
Future<void> disposeLlm() => RustLib.instance.api.crateApiLlmDisposeLlm();

/// `true` when a Gemma model is loaded — used by Dart-side lifecycle.
Future<bool> isGemmaLoaded() => RustLib.instance.api.crateApiLlmIsGemmaLoaded();
